apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: canary-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "canary-app.fullname" . }}-stable
                port:
                  number: 80