apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-app.fullname" . }}-stable
spec:
  selector:
    {{- include "canary-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-app.fullname" . }}-canary
spec:
  selector:
    {{- include "canary-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP