replicaCount: 3

imagePullSecrets:
  - name: ghcr-secret

image:
  repository: ghcr.io/charlie-paterson/canary-demo
  tag: "latest"
  pullPolicy: Always

app:
  version: "1.0.0"
  release: "stable"

service:
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
