replicaCount: 3

image:
  repository: ghcr.io/charlie-paterson/kubernetes-training
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

app:
  version: "1.0.0"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

ingress:
  enabled: true
  className: nginx
  host: ha-app.local
  path: /
  pathType: Prefix
